### ISSUE TITLE
Parsing error in python snippets

### ISSUE THREAD

**Issue by IGI-111** [stevearc/vim-vscode-snippets#1]
Just tried to install and use the snippets but I get the following error:

```
[vsnip] Parsing error occurred on: /home/igi-111/.local/share/nvim/site/pack/paqs/start/vim-vsnip-snippets/snippets/vscode-Python-Extended/modules.json
```

**Comment by stevearc** [comment]
Thanks for the report! That extension had some...very optimistic constructs in its module.json file. I switched to a different extension for the python snippets and confirmed that everything works now.

**Comment by IGI-111** [comment]
It works alright, thanks!
